### ISSUE TITLE
Missing info in "tape it together"

### ISSUE THREAD

**Issue by aleciten** [finnp/test-anything#1]
In **Tape it together** there's no mention of *fancify* being a module whose path is provided in *process.argv[2]*. I had to look at the solution to see what was wrong since there's no "test-anything run" that would allow me to test the code.

**Comment by finnp** [comment]
Thanks a lot! If you find any more confusing parts, I would appreciate more issues or pull requests. :sunflower:

**Comment by aleciten** [comment]
Will do!
