### ISSUE TITLE
LOG IT OUT

### ISSUE THREAD

**Issue by ecasilla** [finnp/test-anything#2]
The instructions say the parameters will be passed on process.argv[2] and  process.argv[3] but the actual solution say process.arg[1] and process.arg[2] I've tired both and node pass ..

I don't think 1 and 2 are possible since the first two elements are the cmd and the path.. But in any case neither solution passes..

Also the first challenge doesn't have a run function maybe it should be refactored to call verify?
ERROR: This problem doesn't have a .run function.

**Comment by finnp** [comment]
Yeah that solution has been wrong. Thanks for the hint! Your solution is working though. Going to publish a new version. Thanks :+1:

**Comment by finnp** [comment]
I also added a "run" function for the first exercise, hadn't implemented them yet.
