### ISSUE TITLE
"To err is human, to purr feline" - `t.throws(petDog('dachshund'))` wrongly suggests providing function call result (rather than function) as argument

### ISSUE THREAD

**Issue by sneakertack** [finnp/test-anything#5]
The provided example `t.throws(petDog('dachshund'))` can lead the student to wrongly conclude that analogous solution for `feedCat` is `t.throws(feedCat('chocolate'))` - which fails because `throws` wants a function to call, not the value/error from an already called function.

Suggest amending example to:

```js
t.throws(function () {
  petDog('dachshund');
})
```

Or alternatively, using `petDog.bind`, like `feedCat.bind` in the solution.

**Comment by finnp** [comment]
Thanks! I fixed that in `1.1.1` with both your version and the `.bind` version explained.
