### ISSUE TITLE
Switch to workshopper-adventure ?

### ISSUE THREAD

**Issue by finnp** [finnp/test-anything#7]
Hey @martinheidegger,

what's the deal with `workshopper-adventure`. Does it make sense to adopt it? What are the benefits? Also is it planned to merge `workshopper-adventure` into `workshopper` at some point?

Best,
Finn

**Comment by martinheidegger** [comment]
`workshopper-adventure` is an unstable release of `workshopper` to test out the new `adventurize` PR with the other people. I can not publish workshopper so for the sake of simplicity I created it just like that. Once [the PR](https://github.com/rvagg/workshopper/pull/106) is merged I will kill the repository.

**Comment by finnp** [comment]
Alright, that's what I thought. I subscribed to that PR. Thanks!
