### ISSUE TITLE
tape it up

### ISSUE THREAD

**Issue by argomez** [finnp/test-anything#8]
I tried tape it up and couldn't get it to work. Eventually went and found the solution and it didn't work either

**Comment by finnp** [comment]
Hey @argomez,

it works for me, could you share the output of `test-anything verify`?

Best,
Finn

**Comment by argomez** [comment]
Andrews-MacBook-Pro:test-anything agomez$ test-anything verify tapeItTogether.js 

TAP version 13
# (anonymous)
ok 1 wrong function not accepted
ok 2 wrong function not accepted
ok 3 wrong function not accepted
not ok 4 correct function accepted
  ---
    operator: ok
    expected: true
    actual:   false
    at: ChildProcess.<anonymous> (/usr/local/lib/node_modules/test-anything/exercises/utils/index.js:32:7)
  ...

1..4
# tests 4
# pass  3
# fail  1

#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################

**Comment by gitting** [comment]
Had the same problem. Installed `tape` locally by `npm install tape` and it worked.

**Comment by finnp** [comment]
@argomez sorry, can you show me the `tapeItTogether.js` as well. I don't see why it should fail.

I also just updated the deps as `1.1.3`. So maybe you could do `npm i test-anything@latest -g` to update it. Maybe that works, since @gitting described to have problems with tape.

**Comment by sudodoki** [comment]
Seeing same issue on MacOS.
node v 0.10.31
Running `test-anything verify tape_solution.js` yields
```
TAP version 13
# (anonymous)
ok 1 wrong function not accepted
ok 2 wrong function not accepted
ok 3 wrong function not accepted
not ok 4 correct function accepted
  ---
    operator: ok
    expected: true
    actual:   false
    at: ChildProcess.<anonymous> (/usr/local/lib/node_modules/test-anything/exercises/utils/index.js:32:7)
  ...

1..4
# tests 4
# pass  3
# fail  1

#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################
```
Content of tape_solution.js is
```
var test = require('tape')
var fancify = require(process.argv[2])

test('fancify', function (t) {
  t.equal(fancify('Wat'), '~*~Wat~*~', 'Wraps a string in ~*~')
  t.equal(fancify('Wat', true), '~*~WAT~*~', 'Optionally makes it allcaps')
  t.equal(fancify('Wat', false, '%'), '~%~Wat~%~', 'Optionally allows to set the character')
  t.end()
})
```
test-anything is version 1.1.3
After installing 'tape' in current folder it passes.
Can make an assumption issue with `tape` module included with the workshopper isn't in the module lookup path.
BTW, if you validate an empty file you will get `# pass  1 # fail  3`
and if you validate one with `throw('Error');` you will have `# pass  3 # fail  1` which I believe is the output displayed in snippet pasted to this thread.

**Comment by finnp** [comment]
Ah, I expect you to install the `tape` module in your project folder. Maybe that should be made more clear in the exercise?

I just added this info: https://github.com/finnp/test-anything/commit/ad2938c6bea9acb3729a1dd1a48e9efe39039aa6

**Comment by frenchbread** [comment]
@finnp Thank you for your comment.
Had the same issue. After `tape` installation got it working.
```npm install tape```

**Comment by finnp** [comment]
:+1:

**Comment by patrickdavey** [comment]
Hi @finnp ,

I am actually still getting this. I have installed tape locally, and I did just update test-anything to the latest version.. My node version is v5.7.0 (on OSX).

```javascript
var test = require('tape')
var fancify = process.argv[2]

test('returns the str wrapped in ~*~', function (t) {
 t.ok(fancify('Hello'), '~*~Hello~*~')
 t.end()
});

test('has an optional second argument to return value in ALLCAPS', function (t) {
 t.ok(fancify('Hello', true), '~*~HELLO~*~')
 t.end()
});

test('has an optional third argument to specify internal char.', function (t) {
 t.ok(fancify('Hello', false, "!"), '~!~Hello~!~')
 t.end()
});

test('can do a falsey test.', function (t) {
 t.notOk(fancify('Hello'), 'Hello')
 t.end()
});
```
error:
```

TAP version 13
# (anonymous)
ok 1 wrong function not accepted
ok 2 wrong function not accepted
ok 3 wrong function not accepted
not ok 4 correct function accepted
  ---
    operator: ok
    expected: true
    actual:   false
    at: ChildProcess.<anonymous> (/usr/local/lib/node_modules/test-anything/exercises/utils/index.js:32:7)
  ...

1..4
# tests 4
# pass  3
# fail  1

#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################
```

I had a look at the code which it said was failing (in /usr/local/lib/node_modules/test-anything/exercises/utils/index.js:32 ) but it didn't mean much to me. For reference it was:

```javascript
  program.on('close', function (code) {
    t.ok(!code, 'correct function accepted')
  })
```
